# -*- coding: utf-8 -*-
"""نصوص البوت بالعربي والإنجليزي / Bilingual UI texts (ar + en)."""

T = {
    # ═══════════════════════ العربية ═══════════════════════
    "ar": {
        # أزرار عامة
        "btn_store": "المتجر", "btn_account": "حسابي", "btn_purchases": "مشترياتي",
        "btn_settings": "الإعدادات", "btn_support": "الدعم", "btn_admin": "لوحة الأدمن",
        "btn_back": "رجوع", "btn_back_admin": "رجوع للوحة", "btn_cancel": "إلغاء",
        "btn_yes": "نعم، تأكيد", "btn_no": "لا، إلغاء", "btn_check": "تحقّق",
        "btn_buy": "شراء الآن", "btn_lang_ar": "العربية", "btn_lang_en": "English",
        "btn_copy_key": "نسخ المفتاح", "btn_copy_link": "نسخ رابط الإحالة",
        "btn_send_contact": "إرسال رقمي للتحقق",

        # البداية والتحقق
        "start_new": "{e:wave} <b>أهلاً بك في متجر المفاتيح!</b>\n\nقبل البدء لازم نتحقق من حسابك — وهي خطوة وحدة بس لأول مرة.",
        "ask_phone": "{e:phone} <b>أرسل رقمك الآن لإكمال التحقق</b>\n\nاضغط الزر بالأسفل لإرسال رقمك تلقائياً، أو أرسله كتابةً بالصيغة الدولية:\n<code>+963912345678</code>",
        "phone_bad": "{e:error} الرقم غير صحيح!\nأرسل رقمك بالصيغة الدولية مثل <code>+963912345678</code> أو استخدم زر «{btn_send_contact}».",
        "phone_other": "{e:error} هذا الرقم تبع حساب ثاني! لازم ترسل رقم <b>حسابك</b> أنت.",
        "phone_ok": "{e:success} <b>تم التحقق من حسابك بنجاح!</b>",
        "banned": "{e:ban} <b>تم حظرك من استخدام هذا البوت!</b>",
        "ban_reason_line": "\n{e:warning} السبب: {reason}",
        "already_reg": "{e:warning} أنت مسجّل من قبل! لا يمكن الاستفادة من رابط إحالة بعد التسجيل.",

        # القنوات الإجبارية
        "gate_hdr": "{e:channel} <b>لازم تنضم للقنوات التالية حتى تستخدم البوت:</b>",
        "gate_after": "\n\nبعد الانضمام اضغط الزر بالأسفل للتحقق.",
        "gate_still": "{e:error} لسلا ما انضممت إلى:\n{list}",
        "gate_passed": "{e:success} <b>تم! أهلاً بك عالسفينة</b>",

        # القائمة الرئيسية
        "menu_txt": "{e:wave} <b>أهلاً {name}</b>\n\n{e:points} نقاطك: <b>{points}</b>\n{e:referral} كل صديق يسجّل عبر رابطك = نقطة لحسابك!\n\n👇 اختر من القائمة:",
        "use_buttons": "{e:warning} استخدم الأزرار بالأسفل فقط 👇",
        "no_access": "{e:ban} لا تملك صلاحية لهذا الأمر!",

        # الحساب
        "account_txt": "{e:account} <b>حسابي</b>\n\n{e:account} الاسم: {name}\n{e:id} الآيدي: <code>{uid}</code>\n{e:phone} الرقم: {phone}\n{e:lang} اللغة: {lang}\n{e:stats} تاريخ الانضمام: {joined}\n\n{e:points} نقاطك: <b>{points}</b>\n{e:referral} أشخاص دعوتهم: <b>{refs}</b>\n{e:box} مشترياتك: <b>{buys}</b>\n{e:money} مجموع إنفاقك: <b>{spent}</b> نقطة",
        "no_phone": "غير مسجّل",
        "ref_link_hint": "\n\n{e:referral} <b>رابط الإحالة تبعك</b> (كل تسجيل عبره = +{reward} نقطة):\n<code>{link}</code>",

        # الإعدادات
        "settings_txt": "{e:settings} <b>الإعدادات</b>\n\n{e:lang} لغتك الحالية: العربية\nاختر اللغة المفضلة:",
        "lang_set": "{e:success} تم تغيير اللغة بنجاح!",

        # المتجر
        "store_hdr": "{e:store} <b>المتجر</b>\n\nاختر قسم:",
        "store_empty": "{e:box} المتجر فاضي حالياً! عوداً لاحقاً.",
        "cat_hdr": "{e:category} <b>{cat}</b>\n\nاختر منتج:",
        "cat_empty": "{e:box} ما في منتجات بهالقسم حالياً.",
        "prod_btn": "{name} — {price}⭐",
        "product_txt": "{e:key} <b>{name}</b>\n\n{e:money} السعر: <b>{price}</b> نقطة\n{e:box} المتوفر: <b>{stock}</b>",
        "out_stock": "{e:error} غير متوفر حالياً",
        "confirm_buy": "{e:warning} <b>تأكيد الشراء</b>\n\n{e:key} المنتج: <b>{name}</b>\n{e:money} السعر: <b>{price}</b> نقطة\n{e:points} رصيدك: <b>{balance}</b> نقطة\n\nراح يوصلک المفتاح فوراً، متأكد؟",
        "no_points": "{e:error} <b>نقاطك غير كافية!</b>\nتحتاج <b>{need}</b> نقطة إضافية.\n\n{e:referral} جمع النقاط سهل: دعوة أصدقائك عبر رابط الإحالة بحسابك، وكل تسجيل = نقطة!",
        "no_stock_buy": "{e:error} للأسف نفدت الكمية من هالمنتج! جرّب لاحقاً.",
        "buy_ok": "{e:success} <b>تم الشراء بنجاح!</b>\n\n{e:key} <b>مفتاحك:</b>\n<code>{key}</code>\n\n{e:warning} احتفظ بالمفتاح ولا تشاركه مع أحد!\n{e:points} رصيدك الآن: <b>{balance}</b> نقطة",

        # المشتريات
        "purchases_hdr": "{e:purchases} <b>مشترياتي</b> (آخر {n})\n\n",
        "purchases_row": "{i}. <b>{name}</b> — {date}\n<code>{key}</code>\n\n",
        "purchases_empty": "{e:box} ما في مشتريات بعد!\nتصفّح المتجر واجمع نقاط من الإحالات.",

        # الدعم
        "support_txt": "{e:support} <b>الدعم الفني</b>\n\nعندك سؤال أو مشكلة؟ تواصل مباشرة مع الأونر من الزر بالأسفل ⬇️",

        # المساعدة
        "help_txt": "{e:wave} <b>أوامر البوت</b>\n/start — تشغيل البوت\n/help — هالرسالة\n/id — آيدي حسابك\n/lang — تغيير اللغة\n\n{e:points} النقاط: بتجمعها عبر رابط الإحالة بحسابك، وبصرفها من المتجر!",

        # إشعارات الإحالة
        "ref_join": "{e:referral} <b>مبروك! انضم {name} عبر رابطك</b>\n{e:points} +{reward} نقطة — رصيدك: <b>{points}</b>",
        "penalty": "{e:warning} <b>خصم نقاط!</b>\n\n{e:account} العضو: {name}\n{e:id} آيديه: <code>{uid}</code>\n{e:channel} القناة: {channel}\n{e:error} السبب: غادر قناة إجبارية وكان مسجّل عبر رابطك\n{e:points} القيمة المخصومة: <b>-{amount}</b> نقطة\n{e:money} رصيدك الآن: <b>{points}</b> نقطة",
        "penalty_zero": "{e:warning} <b>تنبيه!</b>\n\n{e:account} العضو: {name}\n{e:channel} القناة: {channel}\n{e:error} السبب: غادر قناة إجبارية كان مسجّل عبر رابطك\n(الخصم معطّل حالياً = 0 نقطة)",
        "left_warn": "{e:warning} لاحظنا إنك خرجت من قناة إجبارية!\nلازم ترجع تنضم حتى تقدر تستخدم البوت من جديد.",

        # ═══ لوحة الأدمن ═══
        "am_hdr": "{e:admin} <b>لوحة الأدمن</b>\n\nأهلاً {name} — اختر قسم:",
        "am_cats": "الأقسام", "am_prods": "المنتجات", "am_keys": "مخزون المفاتيح",
        "am_stats": "الإحصائيات", "am_ref": "نقاط الإحالة", "am_emoji": "الإيموجيات",
        "am_chan": "القنوات الإجبارية", "am_users": "المستخدمون", "am_bcast": "إذاعة عامة",
        "am_admins": "الأدمنز", "am_backup": "نسخة احتياطية", "am_exit": "خروج للقائمة",

        "no_cats": "ما في أقسام! ابدأ بإضافة قسم.",
        "cat_add_prompt": "{e:add} <b>إضافة قسم جديد</b>\n\nأرسل اسم القسم <b>بالعربي</b>:",
        "cat_add_en_prompt": "ممتاز! هلق أرسل الاسم <b>بالإنجليزي</b>\n(أو أرسل <code>-</code> لاستخدام نفس الاسم):",
        "cat_added": "{e:success} تمت إضافة القسم «{name}»!",
        "cat_ren_prompt": "{e:edit} أرسل الاسم الجديد <b>بالعربي</b> للقسم «{name}»:",
        "cat_ren_en_prompt": "{e:edit} أرسل الاسم الجديد <b>بالإنجليزي</b> للقسم «{name}»:",
        "cat_updated": "{e:success} تم تعديل القسم!",
        "cat_del_confirm": "{e:warning} <b>حذف القسم «{name}»؟</b>\n\n⚠️ رح تُحذف كل منتجاته ومفاتيحه غير المباعة!",
        "cat_deleted": "{e:success} تم حذف القسم ومنتجاته.",

        "prod_name_ar_prompt": "{e:add} <b>إضافة منتج جديد</b>\n\nأرسل اسم المنتج <b>بالعربي</b>:",
        "prod_name_en_prompt": "هلق أرسل اسم المنتج <b>بالإنجليزي</b>\n(أو <code>-</code> لنفس الاسم):",
        "prod_price_prompt": "{e:money} أرسل <b>سعر</b> المنتج بالنقاط (رقم فقط):",
        "prod_added": "{e:success} تمت إضافة المنتج «{name}» بسعر {price} نقطة!",
        "prod_card": "{e:key} <b>{name}</b>\n\n{e:category} القسم: {cat}\n{e:money} السعر: {price} نقطة\n{e:box} المخزون: {stock}\n{e:fire} المباع: {sold}",
        "prod_del_confirm": "{e:warning} <b>حذف المنتج «{name}»؟</b>\nمفاتيحه غير المباعة رح تنحذف.",
        "prod_deleted": "{e:success} تم حذف المنتج.",
        "prod_move_pick": "{e:category} اختر القسم الجديد للمنتج «{name}»:",
        "prod_moved": "{e:success} تم نقل المنتج للقسم «{cat}»!",
        "prod_edit_pick": "{e:edit} شنو بدك تعدّل بـ «{name}»؟",
        "prod_edit_ar": "الاسم العربي", "prod_edit_en": "الاسم الإنجليزي",
        "prod_edit_price": "السعر", "prod_edit_move": "نقل لقسم", "prod_edit_delete": "حذف المنتج",
        "prod_new_name_prompt": "{e:edit} أرسل الاسم الجديد:",
        "prod_updated": "{e:success} تم التعديل!",
        "no_prods": "ما في منتجات! أضف منتج أولاً.",

        "keys_pick": "{e:key} <b>مخزون المفاتيح</b>\n\nاختر منتج لإدارة مخزونه:",
        "keys_card": "{e:key} <b>{name}</b>\n\n{e:box} المفاتيح المتوفرة: <b>{stock}</b>\n{e:fire} المباعة: <b>{sold}</b>",
        "keys_prompt": "{e:add} أرسل المفاتيح الآن، <b>مفتاح بسطر واحد</b>:\n\nمثال:\n<code>ABCD-1234-EFGH\nWXYZ-5678-KLMN</code>",
        "keys_added": "{e:success} تمت إضافة <b>{n}</b> مفتاح إلى «{name}»!\n{e:box} المخزون الآن: <b>{total}</b>",
        "keys_export_caption": "{e:box} مفاتيح «{name}» غير المباعة ({n} مفتاح)",
        "keys_no_stock": "ما في مفاتيح غير مباعة لهالمنتج!",
        "keys_clear_confirm": "{e:warning} <b>حذف كل مفاتيح «{name}» غير المباعة ({stock} مفتاح)؟</b>",
        "keys_cleared": "{e:success} تم حذف {n} مفتاح من المخزون.",

        "stats_txt": "{e:stats} <b>الإحصائيات</b>\n\n{e:users} المستخدمون: <b>{users}</b> (+{today} اليوم)\n{e:success} المحققين: <b>{verified}</b>\n{e:ban} المحظورين: <b>{banned}</b>\n{e:referral} إجمالي الإحالات: <b>{refs}</b>\n{e:points} النقاط المتداولة: <b>{points}</b>\n\n{e:box} المشتريات: <b>{purchases}</b>\n{e:money} الإيرادات: <b>{revenue}</b> نقطة\n{e:key} المفاتيح بالمخزون: <b>{keys}</b>\n\n{e:category} الأقسام: <b>{cats}</b> | المنتجات: <b>{prods}</b>\n{e:channel} القنوات: <b>{channels}</b> | الأدمنز: <b>{admins}</b>\n\n{e:fire} <b>الأكثر مبيعاً:</b>\n{top}",
        "stats_top_empty": "— لا شيء بعد —",
        "stats_top_row": "{i}. {name} — {c} مبيعة ({s} نقطة)\n",

        "ref_txt": "{e:referral} <b>إعدادات نقاط الإحالة</b>\n\n{e:referral} مكافأة كل إحالة: <b>{reward}</b> نقطة\n{e:warning} خصم عند مغادرة قناة: <b>{penalty}</b> نقطة\n{e:support} معرف الدعم: <b>@{support}</b>\n\nاختر لتعديل:",
        "ref_reward_btn": "مكافأة الإحالة: {v}",
        "ref_penalty_btn": "خصم المغادرة: {v}",
        "ref_support_btn": "معرف الدعم: @{v}",
        "ref_num_prompt": "🔢 أرسل القيمة الجديدة <b>(رقم من 0 إلى 10000)</b>:",

        "emoji_txt": "{e:settings} <b>الإيموجيات</b>\n\nاضغط على أي إيموجي لتعديله.\n{e:warning} ملاحظة: الإيموجي البريميوم تظهر بالرسائل إذا كان صاحب البوت مشترك Premium، وإلا بيظهر الحرف العادي تلقائياً.",
        "emoji_slot_txt": "{e:edit} <b>إيموجي: {label}</b> ({slot})\n\n{e:settings} الحرف الحالي: <code>{char}</code>\n{e:id} الآيدي البريميوم: <code>{cid}</code>\n\nشو بدك تعمل؟",
        "emoji_no_cid": "غير مضبوط",
        "emoji_cid_prompt": "{e:id} أرسل <b>آيدي الإيموجي البريميوم</b> (رقم طويل مثل <code>5360481542747122286</code>)\n\n💡 للحصول عليه: حوّل رسالة فيها الإيموجي لبوت مثل @JSONDumpBot وانسخ قيمة custom_emoji_id\n\nلإلغاء الآيدي أرسل <code>-</code>",
        "emoji_cid_bad": "{e:error} آيدي غير صالح! لازم يكون رقماً طويلاً.",
        "emoji_cid_set": "{e:success} تم ضبط الآيدي البريميوم!",
        "emoji_cid_cleared": "{e:success} تم إلغاء الآيدي البريميوم.",
        "emoji_char_prompt": "{e:edit} أرسل الحرف/الإيموجي الجديد (يظهر بالأزرار وكبديل):",
        "emoji_char_set": "{e:success} تم تغيير الحرف!",
        "emoji_reset": "{e:success} تمت الاستعادة للافتراضي!",
        "emoji_test": "🧪 معاينة مباشرة: {e:__SLOT__}",

        "chan_txt": "{e:channel} <b>القنوات الإجبارية</b>\n\nلازم يشترك الجميع بهالقنوات. اضغط 🗑 لحذف:\n\n{list}",
        "chan_empty_list": "ما في قنوات مضافة.",
        "chan_add_prompt": "{e:add} أرسل بيانات القناة بأي شكل:\n• معرف: <code>@channelname</code>\n• رابط: <code>https://t.me/channelname</code>\n• آيدي: <code>-1001234567890</code>\n• أو <b>حوّل لي أي رسالة من القناة</b>",
        "chan_bad": "{e:error} ما قدرت أوصل للقناة! تأكد إنو البوت عضو/أدمن فيها وجرّب ثانية.",
        "chan_added": "{e:success} تمت إضافة قناة «{title}»!\n\n{e:warning} <b>مهم جداً:</b> ارفع البوت <b>أدمن</b> بالقناة حتى يشتغل فحص الاشتراك وخصم نقاط المغادرة!",
        "chan_deleted": "{e:success} تم حذف القناة.",

        "users_pick": "{e:users} <b>المستخدمون</b> — الأحدث أولاً:\n\nاضغط على مستخدم لإدارته، أو ابحث بالآيدي.",
        "user_find_prompt": "{e:id} أرسل <b>آيدي المستخدم</b>، أو حوّل لي رسالة منه:",
        "user_nf": "{e:error} ما لقيت هالمستخدم! لازم يكون فتح البوت وأكمل التسجيل.",
        "user_card": "{e:account} <b>بطاقة المستخدم</b>\n\n{e:account} الاسم: {name}\n{e:id} الآيدي: <code>{uid}</code>\n{e:settings} المعرف: {username}\n{e:phone} الرقم: {phone}\n{e:lang} اللغة: {lang}\n\n{e:points} النقاط: <b>{points}</b>\n{e:referral} إحالاته: <b>{refs}</b>\n{e:box} مشترياته: <b>{buys}</b> ({spent} نقطة)\n{e:stats} انضم: {joined}\n{e:success} موثّق: {verified}\n{e:ban} محظور: {banned}{ban_reason}\n{e:admin} أدمن: {admin}",
        "yes": "نعم", "no": "لا",
        "pts_add_prompt": "{e:add} أرسل <b>عدد النقاط</b> لإضافتها للمستخدم:",
        "pts_sub_prompt": "{e:delete} أرسل <b>عدد النقاط</b> لخصمها من المستخدم:",
        "pts_done": "{e:success} تم! رصيد المستخدم الآن: <b>{points}</b> نقطة",
        "msg_prompt": "{e:purchases} أرسل الرسالة (نص/صورة/أي محتوى) وبتوصل للمستخدم مباشرة:",
        "msg_sent": "{e:success} وصلت الرسالة للمستخدم!",
        "msg_fail": "{e:error} فشل الإرسال! يمكن المستخدم حظّر البوت.",
        "ban_prompt": "{e:ban} أرسل <b>سبب الحظر</b> أو أرسل <code>-</code> للتخطي:",
        "ban_done": "{e:ban} تم حظر المستخدم.",
        "unban_done": "{e:success} تم فك الحظر عن المستخدم.",
        "user_banned_notify": "{e:ban} <b>تم حظرك من البوت!</b>\nالسبب: {reason}",
        "user_unban_notify": "{e:success} <b>تم فك الحظر عنك!</b> أهلاً بعودتك 🎉",

        "admins_txt": "{e:admin} <b>الأدمنز</b> ({n})\n\nاضغط على أدمن لإزالته، أو أضف جديد:",
        "admins_empty": "ما في أدمنز مضافين (أنت الأونر).",
        "admin_add_prompt": "{e:add} أرسل <b>آيدي الأدمن الجديد</b>، أو حوّل لي رسالة منه:",
        "admin_added": "{e:success} تمت إضافة {name} كأدمن!\n{e:warning} تذكير: الأدمن يقدر يعمل كل شي ما عدا إضافة أدمنز.",
        "admin_removed": "{e:success} تمت إزالة الأدمن.",
        "admin_is_you": "هذا أنت يا أونر 😄 ما بينحذف!",
        "admin_new_notify": "{e:admin} <b>تمت ترقيتك إلى أدمن بالبوت!</b>\nافتح البوت وأرسل /admin",
        "admin_del_notify": "{e:warning} تمت إزالتك من قائمة أدمنزة البوت.",

        "bcast_prompt": "{e:channel} <b>إذاعة عامة</b>\n\nأرسل الرسالة اللي بدك تتبعت <b>لكل المستخدمين</b> (نص/صورة/فيديو/أي شي):",
        "bcast_confirm": "{e:warning} رح تتبع الرسالة إلى <b>{n}</b> مستخدم. متأكد؟",
        "bcast_going": "⏳ جاري الإرسال...",
        "bcast_done": "{e:success} تمت الإذاعة!\n{e:success} وصلت: <b>{ok}</b>\n{e:error} فشلت: <b>{fail}</b>",
        "bcast_cancelled": "{e:error} تم إلغاء الإذاعة.",

        "backup_sent": "{e:success} هذي نسخة قاعدة البيانات الحالية.",
        "only_owner": "{e:ban} هالخاصية للأونر فقط!",

        "num_bad": "{e:error} رقم غير صالح! جرّب مرة ثانية.",
        "text_bad": "{e:error} محتوى غير صالح! جرّب مرة ثانية أو اضغط إلغاء.",

        # سجل التعاملات (شات اللوغ) — سطر ثنائي اللغة
        "log_verified": "📱 اكتمال التحقق | Verified\n👤 {name} | 🆔 <code>{uid}</code> | 📱 {phone}",
        "log_new_user": "🆕 مستخدم جديد | New user\n👤 {name} | 🆔 <code>{uid}</code> | @{username}\n📱 {phone}{ref_line}",
        "log_ref_line": "\n🔗 عبر إحالة من: {ref}",
        "log_ref_credit": "🎁 مكافأة إحالة | Referral reward\n👤 {name} انضم عبر رابط {ref}\n➕ +{amount} نقطة → رصيد {ref}: {points}",
        "log_penalty": "⚠️ خصم مغادرة قناة | Leave penalty\n👤 {name} خرج من «{channel}»\n➖ -{amount} نقطة → رصيد {ref}: {points}",
        "log_purchase": "🛒 عملية شراء | Purchase\n👤 {name} | 🆔 <code>{uid}</code>\n📦 {product} | 💰 {price} نقطة\n🔑 {key}",
        "log_ban": "🚫 حظر | Ban\n👤 {name} | 🆔 <code>{uid}</code>\n📝 {reason}",
        "log_unban": "♻️ فك حظر | Unban\n👤 {name} | 🆔 <code>{uid}</code>",
        "log_points": "💰 تعديل نقاط يدوي | Manual points\n👤 {name} | {delta} نقطة → رصيد: {points}",
        "log_cat_add": "📂 إضافة قسم | Category added: {name}",
        "log_cat_del": "🗑 حذف قسم | Category deleted: {name}",
        "log_cat_edit": "✏️ تعديل قسم | Category edited: {name}",
        "log_prod_add": "📦 إضافة منتج | Product added: {name} ({price}⭐)",
        "log_prod_edit": "✏️ تعديل منتج | Product edited: {name}",
        "log_prod_del": "🗑 حذف منتج | Product deleted: {name}",
        "log_keys": "🔑 إضافة مفاتيح | Keys added: +{n} → {name} (stock: {total})",
        "log_keys_clear": "🧹 تصفير مخزون | Stock cleared: {name} (-{n})",
        "log_chan_add": "📢 إضافة قناة | Channel added: {title} ({cid})",
        "log_chan_del": "🗑 حذف قناة | Channel removed: {title} ({cid})",
        "log_setting": "⚙️ تغيير إعداد | Setting changed: {key} = {value}",
        "log_admin_add": "🛡️ إضافة أدمن | Admin added: {name} ({uid})",
        "log_admin_del": "🛡️ إزالة أدمن | Admin removed: {name} ({uid})",
        "log_bcast": "📣 إذاعة | Broadcast: ok={ok}, fail={fail}",
        "log_emoji": "🎨 تعديل إيموجي | Emoji changed: {slot} = {value}",
        "log_backup": "💾 نسخة احتياطية | Backup downloaded",
    },

    # ═══════════════════════ English ═══════════════════════
    "en": {
        "btn_store": "Store", "btn_account": "My Account", "btn_purchases": "My Purchases",
        "btn_settings": "Settings", "btn_support": "Support", "btn_admin": "Admin Panel",
        "btn_back": "Back", "btn_back_admin": "Back to panel", "btn_cancel": "Cancel",
        "btn_yes": "Yes, confirm", "btn_no": "No, cancel", "btn_check": "Check",
        "btn_buy": "Buy now", "btn_lang_ar": "العربية", "btn_lang_en": "English",
        "btn_copy_key": "Copy key", "btn_copy_link": "Copy referral link",
        "btn_send_contact": "Send my number",

        "start_new": "{e:wave} <b>Welcome to the Keys Store!</b>\n\nBefore we start, we need to verify your account — a one-time step only.",
        "ask_phone": "{e:phone} <b>Send your number to complete verification</b>\n\nTap the button below to share it automatically, or type it in international format:\n<code>+963912345678</code>",
        "phone_bad": "{e:error} Invalid number!\nSend it in international format like <code>+963912345678</code> or use the button below.",
        "phone_other": "{e:error} That number belongs to another account! You must send <b>your own</b> number.",
        "phone_ok": "{e:success} <b>Your account has been verified!</b>",
        "banned": "{e:ban} <b>You have been banned from this bot!</b>",
        "ban_reason_line": "\n{e:warning} Reason: {reason}",
        "already_reg": "{e:warning} You are already registered! Referral links only work for new users.",

        "gate_hdr": "{e:channel} <b>You must join the following channels to use the bot:</b>",
        "gate_after": "\n\nAfter joining, tap the button below to check.",
        "gate_still": "{e:error} You haven't joined yet:\n{list}",
        "gate_passed": "{e:success} <b>Done! Welcome aboard</b>",

        "menu_txt": "{e:wave} <b>Hello {name}</b>\n\n{e:points} Your points: <b>{points}</b>\n{e:referral} Every friend who registers via your link = 1 point!\n\n👇 Choose from the menu:",
        "use_buttons": "{e:warning} Please use the buttons below 👇",
        "no_access": "{e:ban} You are not allowed to do this!",

        "account_txt": "{e:account} <b>My Account</b>\n\n{e:account} Name: {name}\n{e:id} ID: <code>{uid}</code>\n{e:phone} Phone: {phone}\n{e:lang} Language: {lang}\n{e:stats} Joined: {joined}\n\n{e:points} Points: <b>{points}</b>\n{e:referral} Referred users: <b>{refs}</b>\n{e:box} Purchases: <b>{buys}</b>\n{e:money} Total spent: <b>{spent}</b> points",
        "no_phone": "not set",
        "ref_link_hint": "\n\n{e:referral} <b>Your referral link</b> (each signup = +{reward} point):\n<code>{link}</code>",

        "settings_txt": "{e:settings} <b>Settings</b>\n\n{e:lang} Current language: English\nPick your language:",
        "lang_set": "{e:success} Language changed successfully!",

        "store_hdr": "{e:store} <b>Store</b>\n\nPick a category:",
        "store_empty": "{e:box} The store is empty for now! Check back later.",
        "cat_hdr": "{e:category} <b>{cat}</b>\n\nPick a product:",
        "cat_empty": "{e:box} No products in this category yet.",
        "prod_btn": "{name} — {price}⭐",
        "product_txt": "{e:key} <b>{name}</b>\n\n{e:money} Price: <b>{price}</b> points\n{e:box} In stock: <b>{stock}</b>",
        "out_stock": "{e:error} Out of stock",
        "confirm_buy": "{e:warning} <b>Confirm purchase</b>\n\n{e:key} Product: <b>{name}</b>\n{e:money} Price: <b>{price}</b> points\n{e:points} Balance: <b>{balance}</b> points\n\nYour key will be delivered instantly. Proceed?",
        "no_points": "{e:error} <b>Not enough points!</b>\nYou need <b>{need}</b> more.\n\n{e:referral} Earning points is easy: invite friends with your referral link (in My Account) — each signup = 1 point!",
        "no_stock_buy": "{e:error} Sorry, this product is out of stock! Try again later.",
        "buy_ok": "{e:success} <b>Purchase completed!</b>\n\n{e:key} <b>Your key:</b>\n<code>{key}</code>\n\n{e:warning} Keep it safe and never share it!\n{e:points} Your balance: <b>{balance}</b> points",

        "purchases_hdr": "{e:purchases} <b>My Purchases</b> (last {n})\n\n",
        "purchases_row": "{i}. <b>{name}</b> — {date}\n<code>{key}</code>\n\n",
        "purchases_empty": "{e:box} No purchases yet!\nBrowse the store and collect referral points.",

        "support_txt": "{e:support} <b>Support</b>\n\nQuestions or issues? Contact the owner directly via the button below ⬇️",

        "help_txt": "{e:wave} <b>Bot commands</b>\n/start — start the bot\n/help — this message\n/id — your account ID\n/lang — change language\n\n{e:points} Points: collect them via your referral link and spend them in the store!",

        "ref_join": "{e:referral} <b>Congrats! {name} joined via your link</b>\n{e:points} +{reward} point — balance: <b>{points}</b>",
        "penalty": "{e:warning} <b>Points deducted!</b>\n\n{e:account} Member: {name}\n{e:id} ID: <code>{uid}</code>\n{e:channel} Channel: {channel}\n{e:error} Reason: left a mandatory channel after joining via your link\n{e:points} Deducted: <b>-{amount}</b> point(s)\n{e:money} Your balance: <b>{points}</b> points",
        "penalty_zero": "{e:warning} <b>Heads up!</b>\n\n{e:account} Member: {name}\n{e:channel} Channel: {channel}\n{e:error} Reason: left a mandatory channel after joining via your link\n(deduction is disabled = 0 points)",
        "left_warn": "{e:warning} We noticed you left a mandatory channel!\nJoin back to keep using the bot.",

        # ═══ Admin panel ═══
        "am_hdr": "{e:admin} <b>Admin Panel</b>\n\nHello {name} — pick a section:",
        "am_cats": "Categories", "am_prods": "Products", "am_keys": "Key Stock",
        "am_stats": "Statistics", "am_ref": "Referral Points", "am_emoji": "Emojis",
        "am_chan": "Mandatory Channels", "am_users": "Users", "am_bcast": "Broadcast",
        "am_admins": "Admins", "am_backup": "Database Backup", "am_exit": "Exit to menu",

        "no_cats": "No categories yet! Add one first.",
        "cat_add_prompt": "{e:add} <b>New category</b>\n\nSend the category name <b>in Arabic</b>:",
        "cat_add_en_prompt": "Great! Now send the name <b>in English</b>\n(or send <code>-</code> to reuse the same name):",
        "cat_added": "{e:success} Category «{name}» added!",
        "cat_ren_prompt": "{e:edit} Send the new name <b>in Arabic</b> for «{name}»:",
        "cat_ren_en_prompt": "{e:edit} Send the new name <b>in English</b> for «{name}»:",
        "cat_updated": "{e:success} Category updated!",
        "cat_del_confirm": "{e:warning} <b>Delete category «{name}»?</b>\n\n⚠️ All its products and unsold keys will be deleted!",
        "cat_deleted": "{e:success} Category and its products deleted.",

        "prod_name_ar_prompt": "{e:add} <b>New product</b>\n\nSend the product name <b>in Arabic</b>:",
        "prod_name_en_prompt": "Now send the product name <b>in English</b>\n(or <code>-</code> to reuse the Arabic name):",
        "prod_price_prompt": "{e:money} Send the product <b>price in points</b> (number only):",
        "prod_added": "{e:success} Product «{name}» added at {price} points!",
        "prod_card": "{e:key} <b>{name}</b>\n\n{e:category} Category: {cat}\n{e:money} Price: {price} points\n{e:box} Stock: {stock}\n{e:fire} Sold: {sold}",
        "prod_del_confirm": "{e:warning} <b>Delete product «{name}»?</b>\nIts unsold keys will be deleted.",
        "prod_deleted": "{e:success} Product deleted.",
        "prod_move_pick": "{e:category} Pick the new category for «{name}»:",
        "prod_moved": "{e:success} Product moved to «{cat}»!",
        "prod_edit_pick": "{e:edit} What do you want to edit in «{name}»?",
        "prod_edit_ar": "Arabic name", "prod_edit_en": "English name",
        "prod_edit_price": "Price", "prod_edit_move": "Move to category", "prod_edit_delete": "Delete product",
        "prod_new_name_prompt": "{e:edit} Send the new name:",
        "prod_updated": "{e:success} Updated!",
        "no_prods": "No products! Add a product first.",

        "keys_pick": "{e:key} <b>Key Stock</b>\n\nPick a product to manage its stock:",
        "keys_card": "{e:key} <b>{name}</b>\n\n{e:box} Available keys: <b>{stock}</b>\n{e:fire} Sold: <b>{sold}</b>",
        "keys_prompt": "{e:add} Send the keys now, <b>one key per line</b>:\n\nExample:\n<code>ABCD-1234-EFGH\nWXYZ-5678-KLMN</code>",
        "keys_added": "{e:success} Added <b>{n}</b> keys to «{name}»!\n{e:box} Stock is now: <b>{total}</b>",
        "keys_export_caption": "{e:box} Unsold keys of «{name}» ({n} keys)",
        "keys_no_stock": "No unsold keys for this product!",
        "keys_clear_confirm": "{e:warning} <b>Delete all unsold keys of «{name}» ({stock} keys)?</b>",
        "keys_cleared": "{e:success} Deleted {n} keys from stock.",

        "stats_txt": "{e:stats} <b>Statistics</b>\n\n{e:users} Users: <b>{users}</b> (+{today} today)\n{e:success} Verified: <b>{verified}</b>\n{e:ban} Banned: <b>{banned}</b>\n{e:referral} Total referrals: <b>{refs}</b>\n{e:points} Points in circulation: <b>{points}</b>\n\n{e:box} Purchases: <b>{purchases}</b>\n{e:money} Revenue: <b>{revenue}</b> points\n{e:key} Keys in stock: <b>{keys}</b>\n\n{e:category} Categories: <b>{cats}</b> | Products: <b>{prods}</b>\n{e:channel} Channels: <b>{channels}</b> | Admins: <b>{admins}</b>\n\n{e:fire} <b>Best sellers:</b>\n{top}",
        "stats_top_empty": "— nothing yet —",
        "stats_top_row": "{i}. {name} — {c} sold ({s} points)\n",

        "ref_txt": "{e:referral} <b>Referral points settings</b>\n\n{e:referral} Reward per referral: <b>{reward}</b>\n{e:warning} Leave penalty: <b>{penalty}</b>\n{e:support} Support username: <b>@{support}</b>\n\nPick one to edit:",
        "ref_reward_btn": "Referral reward: {v}",
        "ref_penalty_btn": "Leave penalty: {v}",
        "ref_support_btn": "Support: @{v}",
        "ref_num_prompt": "🔢 Send the new value <b>(0 to 10000)</b>:",

        "emoji_txt": "{e:settings} <b>Emojis</b>\n\nTap any emoji to edit it.\n{e:warning} Note: premium emojis appear in messages if the bot owner has Telegram Premium; otherwise the plain char shows automatically.",
        "emoji_slot_txt": "{e:edit} <b>Emoji: {label}</b> ({slot})\n\n{e:settings} Current char: <code>{char}</code>\n{e:id} Premium ID: <code>{cid}</code>\n\nWhat do you want to do?",
        "emoji_no_cid": "not set",
        "emoji_cid_prompt": "{e:id} Send the <b>premium custom emoji ID</b> (a long number like <code>5360481542747122286</code>)\n\n💡 To get it: forward a message containing the emoji to a bot like @JSONDumpBot and copy the custom_emoji_id value\n\nSend <code>-</code> to clear it",
        "emoji_cid_bad": "{e:error} Invalid ID! It must be a long number.",
        "emoji_cid_set": "{e:success} Premium ID set!",
        "emoji_cid_cleared": "{e:success} Premium ID cleared.",
        "emoji_char_prompt": "{e:edit} Send the new char/emoji (used in buttons and as fallback):",
        "emoji_char_set": "{e:success} Char changed!",
        "emoji_reset": "{e:success} Restored to default!",
        "emoji_test": "🧪 Live preview: {e:__SLOT__}",

        "chan_txt": "{e:channel} <b>Mandatory channels</b>\n\nEveryone must join these. Tap 🗑 to remove:\n\n{list}",
        "chan_empty_list": "No channels added.",
        "chan_add_prompt": "{e:add} Send the channel info in any form:\n• Username: <code>@channelname</code>\n• Link: <code>https://t.me/channelname</code>\n• ID: <code>-1001234567890</code>\n• Or <b>forward any message from the channel</b>",
        "chan_bad": "{e:error} Could not access the channel! Make sure the bot is a member/admin there and try again.",
        "chan_added": "{e:success} Channel «{title}» added!\n\n{e:warning} <b>Very important:</b> promote the bot to <b>admin</b> in the channel so join-checks and leave-penalties work!",
        "chan_deleted": "{e:success} Channel removed.",

        "users_pick": "{e:users} <b>Users</b> — newest first:\n\nTap a user to manage them, or search by ID.",
        "user_find_prompt": "{e:id} Send the <b>user ID</b>, or forward a message from them:",
        "user_nf": "{e:error} User not found! They must have opened the bot and registered.",
        "user_card": "{e:account} <b>User Card</b>\n\n{e:account} Name: {name}\n{e:id} ID: <code>{uid}</code>\n{e:settings} Username: {username}\n{e:phone} Phone: {phone}\n{e:lang} Language: {lang}\n\n{e:points} Points: <b>{points}</b>\n{e:referral} Referrals: <b>{refs}</b>\n{e:box} Purchases: <b>{buys}</b> ({spent} points)\n{e:stats} Joined: {joined}\n{e:success} Verified: {verified}\n{e:ban} Banned: {banned}{ban_reason}\n{e:admin} Admin: {admin}",
        "yes": "Yes", "no": "No",
        "pts_add_prompt": "{e:add} Send the <b>number of points</b> to add:",
        "pts_sub_prompt": "{e:delete} Send the <b>number of points</b> to deduct:",
        "pts_done": "{e:success} Done! User balance: <b>{points}</b> points",
        "msg_prompt": "{e:purchases} Send the message (text/photo/anything) to deliver to the user:",
        "msg_sent": "{e:success} Message delivered!",
        "msg_fail": "{e:error} Delivery failed! The user may have blocked the bot.",
        "ban_prompt": "{e:ban} Send the <b>ban reason</b> or send <code>-</code> to skip:",
        "ban_done": "{e:ban} User banned.",
        "unban_done": "{e:success} User unbanned.",
        "user_banned_notify": "{e:ban} <b>You have been banned from the bot!</b>\nReason: {reason}",
        "user_unban_notify": "{e:success} <b>Your ban has been lifted!</b> Welcome back 🎉",

        "admins_txt": "{e:admin} <b>Admins</b> ({n})\n\nTap an admin to remove them, or add a new one:",
        "admins_empty": "No admins added yet (you are the owner).",
        "admin_add_prompt": "{e:add} Send the <b>new admin's ID</b>, or forward a message from them:",
        "admin_added": "{e:success} {name} is now an admin!\n{e:warning} Reminder: admins can do everything except managing admins.",
        "admin_removed": "{e:success} Admin removed.",
        "admin_is_you": "That's you, owner 😄 Can't be removed!",
        "admin_new_notify": "{e:admin} <b>You have been promoted to bot admin!</b>\nOpen the bot and send /admin",
        "admin_del_notify": "{e:warning} You have been removed from the bot's admin list.",

        "bcast_prompt": "{e:channel} <b>Broadcast</b>\n\nSend the message you want delivered <b>to all users</b> (text/photo/video/anything):",
        "bcast_confirm": "{e:warning} The message will be sent to <b>{n}</b> users. Confirm?",
        "bcast_going": "⏳ Sending...",
        "bcast_done": "{e:success} Broadcast finished!\n{e:success} Delivered: <b>{ok}</b>\n{e:error} Failed: <b>{fail}</b>",
        "bcast_cancelled": "{e:error} Broadcast cancelled.",

        "backup_sent": "{e:success} Here is the current database backup.",
        "only_owner": "{e:ban} Owner only!",

        "num_bad": "{e:error} Invalid number! Try again.",
        "text_bad": "{e:error} Invalid content! Try again or press cancel.",

        "log_verified": "📱 Verified | اكتمال التحقق\n👤 {name} | 🆔 <code>{uid}</code> | 📱 {phone}",
        "log_new_user": "🆕 New user | مستخدم جديد\n👤 {name} | 🆔 <code>{uid}</code> | @{username}\n📱 {phone}{ref_line}",
        "log_ref_line": "\n🔗 Referred by: {ref}",
        "log_ref_credit": "🎁 Referral reward | مكافأة إحالة\n👤 {name} joined via {ref}'s link\n➕ +{amount} → {ref} balance: {points}",
        "log_penalty": "⚠️ Leave penalty | خصم مغادرة قناة\n👤 {name} left «{channel}»\n➖ -{amount} → {ref} balance: {points}",
        "log_purchase": "🛒 Purchase | عملية شراء\n👤 {name} | 🆔 <code>{uid}</code>\n📦 {product} | 💰 {price} pts\n🔑 {key}",
        "log_ban": "🚫 Ban | حظر\n👤 {name} | 🆔 <code>{uid}</code>\n📝 {reason}",
        "log_unban": "♻️ Unban | فك حظر\n👤 {name} | 🆔 <code>{uid}</code>",
        "log_points": "💰 Manual points | تعديل نقاط\n👤 {name} | {delta} pts → balance: {points}",
        "log_cat_add": "📂 Category added | إضافة قسم: {name}",
        "log_cat_del": "🗑 Category deleted | حذف قسم: {name}",
        "log_cat_edit": "✏️ Category edited | تعديل قسم: {name}",
        "log_prod_add": "📦 Product added | إضافة منتج: {name} ({price}⭐)",
        "log_prod_edit": "✏️ Product edited | تعديل منتج: {name}",
        "log_prod_del": "🗑 Product deleted | حذف منتج: {name}",
        "log_keys": "🔑 Keys added | إضافة مفاتيح: +{n} → {name} (stock: {total})",
        "log_keys_clear": "🧹 Stock cleared | تصفير مخزون: {name} (-{n})",
        "log_chan_add": "📢 Channel added | إضافة قناة: {title} ({cid})",
        "log_chan_del": "🗑 Channel removed | حذف قناة: {title} ({cid})",
        "log_setting": "⚙️ Setting changed | تغيير إعداد: {key} = {value}",
        "log_admin_add": "🛡️ Admin added | إضافة أدمن: {name} ({uid})",
        "log_admin_del": "🛡️ Admin removed | إزالة أدمن: {name} ({uid})",
        "log_bcast": "📣 Broadcast | إذاعة: ok={ok}, fail={fail}",
        "log_emoji": "🎨 Emoji changed | تعديل إيموجي: {slot} = {value}",
        "log_backup": "💾 Backup downloaded | نسخة احتياطية",
    },
}


def tr(lang: str) -> dict:
    return T.get(lang) or T["ar"]


def t(lang: str, key: str) -> str:
    d = tr(lang)
    return d.get(key) or T["ar"].get(key, key)
